### PR TITLE
Adding bootstrap schemas for all views

### PR DESCRIPTION
**Pull request by kotharironak**
ServiceManager is used by the local mode setup of HT. As part of improving startup and reducing containers, HT related views will be created as part of the image.
pros:
- one less container, reduction in images, part of bootstrap of pinot itself so less failure, 
cons: 
- little manual maintenance overhead if we have to introduce new columns or views in for HT local setup.

### CODE REVIEW

**Comment by kotharironak** [comment]
@tim-mwangi Yes only in HT local mode setup. It won't change anything for SaaS or other modes of deployment.
The above schema is under the service-manager. Here, we will add a script to bootstrap it as part of the image.

**Comment by buchi-busireddy** [comment]
@kotharironak why don't we create Pinot tables as a part of the all-viewgen under a flag? You can do that either in the startup or lazily before producing the first record.

That way, you don't have to duplicate the schema anywhere and the producer of views will take care of making sure that the tables do exist.

**Comment by adriancole** [comment]
The full rationale for this isn't quite captured. Basically all-views-creator is a templating engine that converts hocon to the effectively same json used by pinot directly.

In OSS, there's no need to have a separate tool for this, especially as that tool is the heaviest tool in the stack. I don't expect it to be normal to invent new tools when the vendor tools operate easier and with less dependencies.

For example, Pinot supports PUT semantics already so it is far easier to update running schema using their own tools vs trying to figure out client side which specifically changed.

OSS is in a distinct release schedule and when a release occurs, which schema files need to run PUT again can be noted. Someone can use a tool as easy as pinot's existing ones or invent a new tool as they see fit.

The concern about automatically doing this in view generator.. view generator and this image will move to the hypertrace-ingester repo anyway. this just performs the step in place before that occurs.

**Comment by adriancole** [comment]
will sort this one out before implementing a docker layer to apply the schema as otherwise it is messy https://github.com/hypertrace/pinot/pull/24

**Comment by adriancole** [comment]
now that https://github.com/hypertrace/pinot/pull/24 is in, I can make a layer in docker for the schema and delete the last gnarly config from our docker setup. https://github.com/hypertrace/hypertrace/blob/main/docker/docker-compose.yml#L118-L148


This will massively improve reliability as very often things fail related to this interaction, whether it is ordering problems or the huge size of the job (or huge size of the container). When this done, depending on pinot is already depending on the view creation completed.

**Comment by adriancole** [comment]
I need to verify if there is a side effect in ZK from schema installation. If so, the only way is to do this lazy start of the image vs an image layer (although the "initial schema" certainly can live as a layer).

**Comment by adriancole** [comment]
raised this as it seems a docker layer won't work as certain state is shared between the data directories and ZK. That said I will verify anyway :) https://github.com/apache/incubator-pinot/issues/5977

**Comment by adriancole** [comment]
merging the schema as the approach used to do this is the more interesting thing

**Pull request merged**
